# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [2]:
url = "https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv"
iff = pd.read_csv(url)
iff.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
1,2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2,2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
3,2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
4,2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0

### Step 4.  What is the frequency of the dataset?

In [3]:
pd.infer_freq(pd.to_datetime(iff["Date"]))

### Step 5. Set the column Date as the index.

In [4]:
iff["Date"] = pd.to_datetime(iff["Date"])
iff = iff.set_index("Date")
iff.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0

### Step 6. What is the type of the index?

In [5]:
type(iff.index)

pandas.core.indexes.datetimes.DatetimeIndex

### Step 7. Set the index to a DatetimeIndex type

In [6]:
iff.index = pd.to_datetime(iff.index)
type(iff.index)

pandas.core.indexes.datetimes.DatetimeIndex

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [8]:
monthly = iff.resample("ME").sum()
monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-31,-18387,-16805.0,-1582,3188.0,8688,6841.0,1849,-6510.0
2011-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2011-12-31,-23657,-16659.0,-6999,2395.0,13817,9335.0,4483,-7443.0
2012-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2012-02-29,0,0.0,0,0.0,0,0.0,0,0.0

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [9]:
monthly = monthly.dropna()
monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-31,-18387,-16805.0,-1582,3188.0,8688,6841.0,1849,-6510.0
2011-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2011-12-31,-23657,-16659.0,-6999,2395.0,13817,9335.0,4483,-7443.0
2012-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2012-02-29,0,0.0,0,0.0,0,0.0,0,0.0

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [11]:
yearly = monthly.resample("YE").sum()
yearly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-12-31,-42044,-33464.0,-8581,5583.0,22505,16176.0,6332,-13953.0
2012-12-31,-23929,-22012.0,-1915,785.0,9828,12491.0,-2663,-13316.0
2013-12-31,8052,-5562.0,13615,4180.0,-24460,-14209.0,-10251,-12227.0
2014-12-31,-17011,-15124.0,-1887,-6141.0,-14400,-19014.0,4614,-37552.0
2015-12-31,-36337,-25116.0,-11221,-12474.0,-28678,-34571.0,5893,-77489.0

### BONUS: Create your own question and answer it.