# Getting Financial Data - Google Finance

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
from datetime import datetime

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is)

In [2]:
start = "2015-01-01"
end = pd.Timestamp.today().normalize()
start, end

('2015-01-01', Timestamp('2026-01-22 00:00:00'))

### Step 3. Select the Apple, Tesla, Twitter, IBM, LinkedIn stocks symbols and assign them to a variable called stocks

In [3]:
stocks = ["AAPL.US", "TSLA.US", "TWTR.US", "IBM.US", "LNKD.US"]
stocks

['AAPL.US', 'TSLA.US', 'TWTR.US', 'IBM.US', 'LNKD.US']

### Step 4. Read the data from google, assign to df and print it

In [12]:
data = {}

for s in stocks:
    url = f"https://stooq.com/q/d/l/?s={s.lower()}&i=d"
    tmp = pd.read_csv(url)

    # If the download didn't return proper data, skip this ticker
    if tmp.empty or "Date" not in tmp.columns:
        print("Skipped (no data):", s)
        continue

    tmp["Date"] = pd.to_datetime(tmp["Date"])
    tmp = tmp.set_index("Date").sort_index()
    tmp = tmp.loc[start:end]

    data[s] = tmp

df = pd.concat(data, axis=1)
df.head()

Skipped (no data): TWTR.US
Skipped (no data): LNKD.US

            AAPL.US                                        TSLA.US           \
               Open     High      Low    Close     Volume     Open     High
Date
2015-01-02  24.7765  24.7882  23.8816  24.3203  239141317  14.8580  14.8833
2015-01-05  24.0857  24.1625  23.4499  23.6361  288860738  14.3000  14.4333
2015-01-06  23.7270  23.8975  23.2735  23.6381  295587842  14.0040  14.2800
2015-01-07  23.8500  24.0639  23.7319  23.9734  180109954  14.2233  14.3187
2015-01-08  24.2983  24.9519  24.1754  24.8927  266728489  14.1873  14.2533

                                         IBM.US                             \
                Low    Close    Volume     Open     High      Low    Close
Date
2015-01-02  14.2173  14.6207  71461545  113.958  115.383  113.773  114.544
2015-01-05  13.8107  14.0060  80488110  113.948  113.948  112.465  112.709
2015-01-06  13.6140  14.0853  93924045  112.836  113.041  109.635  110.269
2015-01-07  13.9853  14.0633  44514750  111.050  111.050  108.854  109.567
2015-01-08  14.0007  14.0413  51634560  110.387  112.377  109.909  111.928


                  Volume
Date
2015-01-02  7.819521e+06
2015-01-05  6.906071e+06
2015-01-06  8.698870e+06
2015-01-07  6.653528e+06
2015-01-08  6.001319e+06

### Step 5.  What is the type of structure of df ?

In [6]:
type(df)

pandas.core.frame.DataFrame

### Step 6. Print all the Items axis values
#### To learn more about the Panel structure go to [documentation](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#panel)

In [7]:
df.columns.get_level_values(0).unique()

Index(['AAPL.US', 'TSLA.US', 'IBM.US'], dtype='object')

### Step 7. Good, now we know  the data avaiable. Create a dataFrame called vol, with the Volume values.

In [8]:
vol = df.xs("Volume", level=1, axis=1)
vol.head()

              AAPL.US   TSLA.US        IBM.US
Date
2015-01-02  239141317  71461545  7.819521e+06
2015-01-05  288860738  80488110  6.906071e+06
2015-01-06  295587842  93924045  8.698870e+06
2015-01-07  180109954  44514750  6.653528e+06
2015-01-08  266728489  51634560  6.001319e+06

### Step 8. Aggregate the data of Volume to weekly
#### Hint: Be careful to not sum data from the same week of 2015 and other years.

In [9]:
vol_weekly = vol.resample("W").sum()
vol_weekly.head()

               AAPL.US    TSLA.US        IBM.US
Date
2015-01-04   239141317   71461545  7.819521e+06
2015-01-11  1272625963  340584240  3.461174e+07
2015-01-18  1366582546  461503110  3.292134e+07
2015-01-25  1187791933  322860375  4.420538e+07
2015-02-01  2096051575  235304400  4.654072e+07

### Step 9. Find all the volume traded in the year of 2015

In [10]:
vol_2015 = vol.loc["2015"]
vol_2015

              AAPL.US   TSLA.US        IBM.US
Date
2015-01-02  239141317  71461545  7.819521e+06
2015-01-05  288860738  80488110  6.906071e+06
2015-01-06  295587842  93924045  8.698870e+06
2015-01-07  180109954  44514750  6.653528e+06
2015-01-08  266728489  51634560  6.001319e+06
...               ...       ...           ...
2015-12-24   60098492  10654155  2.049145e+06
2015-12-28  118034904  28519560  4.307907e+06
2015-12-29  136718750  36094350  5.404663e+06
2015-12-30   98331163  46861110  4.096771e+06
2015-12-31  171629747  37546545  4.743742e+06

[252 rows x 3 columns]

### BONUS: Create your own question and answer it.