# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [35]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [36]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [37]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [ ]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "", regex=False).astype(float)

above_10_dollars = chipo[chipo["item_price"] > 10].shape[0]
above_10_dollars

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [42]:
chipo[["item_name", "item_price"]].drop_duplicates()

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4237                    Chips and Guacamole        8.50
4354                       Steak Soft Tacos       18.50
4489                    Chips and Guacamole       17.80
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [44]:
chipo[["item_name", "item_price"]].drop_duplicates().sort_values(by="item_name")

              item_name  item_price
3389  6 Pack Soft Drink       12.98
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
3195      Barbacoa Bowl        8.69
95        Barbacoa Bowl        9.25
...                 ...         ...
186   Veggie Salad Bowl       11.25
3889  Veggie Soft Tacos       16.98
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75
1395  Veggie Soft Tacos        8.49

[209 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered?

In [55]:
max_price = chipo["item_price"].max()
# max_price

max_price_qty = chipo.loc[chipo["item_price"] == max_price, "quantity"].sum()
max_price_qty

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [56]:
vsb_qty = chipo.loc[chipo["item_name"] == "Veggie Salad Bowl", "quantity"].sum()
vsb_qty

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [ ]:
canned_soda = chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]   # shape[0] ~ No. of Rows
canned_soda

20