# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [9]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [10]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
users = pd.read_csv(url, sep="|", names=["user_id", "age", "gender", "occupation", "zip_code"], index_col="user_id")

users.head()

         age  gender  occupation  zip_code
user_id
user_id  age  gender  occupation  zip_code
1         24       M  technician     85711
2         53       F       other     94043
3         23       M      writer     32067
4         24       M  technician     43537

In [11]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Index: 944 entries, user_id to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         944 non-null    object
 1   gender      944 non-null    object
 2   occupation  944 non-null    object
 3   zip_code    944 non-null    object
dtypes: object(4)
memory usage: 36.9+ KB

### Step 4. Discover what is the mean age per occupation

In [33]:
# Convert age column to numeric
users["age"] = pd.to_numeric(users["age"])

In [34]:
users.groupby("occupation")["age"].mean().sort_values(ascending=False)

occupation
retired          63.071429
doctor           43.571429
educator         42.010526
healthcare       41.562500
librarian        40.000000
administrator    38.746835
executive        38.718750
marketing        37.615385
lawyer           36.750000
engineer         36.388060
writer           36.311111
salesman         35.666667
scientist        35.548387
other            34.523810
technician       33.148148
programmer       33.121212
homemaker        32.571429
artist           31.392857
entertainment    29.222222
none             26.555556
student          22.081633
occupation             NaN
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [41]:
a = users[users["gender"] == "M"].groupby("occupation").size()

In [40]:
b = users.groupby("occupation").size()

In [39]:
a / b

occupation
administrator    0.544304
artist           0.535714
doctor           1.000000
educator         0.726316
engineer         0.970149
entertainment    0.888889
executive        0.906250
healthcare       0.312500
homemaker        0.142857
lawyer           0.833333
librarian        0.431373
marketing        0.615385
none             0.555556
occupation            NaN
other            0.657143
programmer       0.909091
retired          0.928571
salesman         0.750000
scientist        0.903226
student          0.693878
technician       0.962963
writer           0.577778
dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [23]:
users.groupby("occupation")["age"].agg(["min", "max"])

                min   max
occupation
administrator  21.0  70.0
artist         19.0  48.0
doctor         28.0  64.0
educator       23.0  63.0
engineer       22.0  70.0
entertainment  15.0  50.0
executive      22.0  69.0
healthcare     22.0  62.0
homemaker      20.0  50.0
lawyer         21.0  53.0
librarian      23.0  69.0
marketing      24.0  55.0
none           11.0  55.0
occupation      NaN   NaN
other          13.0  64.0
programmer     20.0  63.0
retired        51.0  73.0
salesman       18.0  66.0
scientist      23.0  55.0
student         7.0  42.0
technician     21.0  55.0
writer         18.0  60.0

### Step 7. For each combination of occupation and gender, calculate the mean age

In [28]:
users.groupby(["occupation", "gender"])["age"].mean()

occupation     gender
administrator  F         40.638889
               M         37.162791
artist         F         30.307692
               M         32.333333
doctor         M         43.571429
educator       F         39.115385
               M         43.101449
engineer       F         29.500000
               M         36.600000
entertainment  F         31.000000
               M         29.000000
executive      F         44.000000
               M         38.172414
healthcare     F         39.818182
               M         45.400000
homemaker      F         34.166667
               M         23.000000
lawyer         F         39.500000
               M         36.200000
librarian      F         40.000000
               M         40.000000
marketing      F         37.200000
               M         37.875000
none           F         36.500000
               M         18.600000
occupation     gender          NaN
other          F         35.472222
               M         34.028986
programmer     F         32.166667
               M         33.216667
retired        F         70.000000
               M         62.538462
salesman       F         27.000000
               M         38.555556
scientist      F         28.333333
               M         36.321429
student        F         20.750000
               M         22.669118
technician     F         38.000000
               M         32.961538
writer         F         37.631579
               M         35.346154
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [46]:
male = users[users["gender"] == "M"].groupby("occupation").size()
female = users[users["gender"] == "F"].groupby("occupation").size() 
total = users.groupby("occupation").size()

(male / total) * 100
(female / total) * 100

occupation
administrator    45.569620
artist           46.428571
doctor                 NaN
educator         27.368421
engineer          2.985075
entertainment    11.111111
executive         9.375000
healthcare       68.750000
homemaker        85.714286
lawyer           16.666667
librarian        56.862745
marketing        38.461538
none             44.444444
occupation             NaN
other            34.285714
programmer        9.090909
retired           7.142857
salesman         25.000000
scientist         9.677419
student          30.612245
technician        3.703704
writer           42.222222
dtype: float64